
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.11.3-arch1-1 - x86_64
...
